config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reviews
  resources :movies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "movies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews
  belongs_to :user
  validates  :title, :image, presence:true
  validates :title, uniqueness: true
  has_one_attached :image
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user
  validates  :rating, presence:true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :movies
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @review = Review.new
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :director, :rating, :actors, :image, :user_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment, :movie_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <a class="navbar-brand" href="<%= root_path %>">Movie Reviews</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
				<li class="nav-item"><%= link_to "New Movie", new_movie_path, class: "nav-link" %></li>
				<li class="nav-item"><%= link_to "Account", edit_user_registration_path, class: "nav-link" %></li>
				<li class="nav-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %> </li>
			<% else %>
				<li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
				<li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: "nav-link" %></li>
			<% end %>
    </ul>
		<% if user_signed_in? %>
			<span class="navbar-text">
				Logged in as <strong><%= current_user.email %>
			</span>		
		<% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    		  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"> -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/header' %>
    
    <div class="container">
      
      
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
     
      
    <%= yield %>
      </div>
      
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :movie_length %>
    <%= form.text_field :movie_length, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :actors %>
    <%= form.text_field :actors, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <%= hidden_field_tag 'movie[user_id]', current_user.id %>

  <div class="actions">
    <%= form.submit "Add Movie", class:"btn btn-danger"%>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<% if !user_signed_in? %>
	  <div class="jumbotron">
	    <h1>Your Favorite Movies Reviewed</h1>
	    <p><%= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
	  </div>
<% end %>

<div class="row">
	  <% @movies.each do |movie| %>
	    <div class="col-sm-6 col-md-3">
	      <div class="img-thumbnail">
	        <%= link_to (image_tag movie.image, class: 'image', style:"width:100%"), movie %>
	      </div>
	    </div>
	  <% end %>
</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
	<div class="panel panel-default">
	  <div class="panel-body">
	    <div class="row">
	      <div class="col-md-4">
          <%= image_tag @movie.image, style: "width: 100%" %>
          
          <div class="star-rating" data-score= <%= @avg_review %> ></div>
	        <em><%= "#{@reviews.length} reviews" %></em>
          
	        <div class="table-responsive">
	          <table class="table">
	            <tbody>
	              <tr>
	                <td><strong>Title:</strong></td>
	                <td><%= @movie.title %></td>
	              </tr>
	              <tr>
	                <td><strong>Description:</strong></td>
	                <td><%= @movie.description %></td>
	              </tr>
	              <tr>
	                <td><strong>Movie length:</strong></td>
	                <td><%= @movie.movie_length %></td>
	              </tr>
	              <tr>
	                <td><strong>Director:</strong></td>
	                <td><%= @movie.director %></td>
	              </tr>
	              <tr>
	                <td><strong>Rating:</strong></td>
	                <td><%= @movie.rating %></td>
	              </tr>
	            </tbody>
	          </table>
	          <%#= link_to "Write a Review", new_movie_review_path(@movie) %>
	        </div>
	      </div>
	      <div class="col-md-7 col-md-offset-1">
	        <h1 class="review_title"><%= @movie.title %></h1>
	        <p><%= @movie.description %></p>

	        <% if @reviews.blank? %>
	          <h3>No reviews just yet, would you like to add the first!</h3>
	          <%#= link_to "Write Review", new_movie_review_path(@movie), class: "btn btn-danger" %>
	        <% else %>
	          <% @reviews.each do |review| %>
	            <div class="reviews">
	              <div class="star-rating" data-score= <%= review.rating %> ></div>
	              <p><%= review.comment %></p>
	            </div>
	          <% end %>
	        <% end %>
          
          <% if user_signed_in? %>
					  <%= render 'reviews/form' %>
					<% end %>
          
	      </div>
	    </div>
	  </div>
	</div>

	<%= link_to 'Edit', edit_movie_path(@movie) %> |
	<%= link_to 'Back', movies_path %>

<script>
	  $('#star-rating').raty({
	    path: '/jq/',
	    scoreName: 'review[rating]'
	  });
		
		$('.star-rating').raty({
	      path: '/jq/',
	      readOnly: true,
	      score: function() {
	            return $(this).attr('data-score');
	    }
	  });
	</script>

app/views/reviews/_form.html.erb
<%= form_with(model: @review, local: true) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <%= hidden_field_tag 'review[movie_id]', @movie.id %>
  <%= hidden_field_tag 'review[user_id]', current_user.id %>

  <div class="actions">
    <%= form.submit "Add Review", class:"btn btn-danger"%>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th>Movie</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= review.movie_id %></td>
        <td><%= review.user_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @review.movie_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>